

name: Deploy to Cloud Run

on:
  push:
    branches: [ main ] # Se activa cada vez que subas a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Container
        run: |-
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/inflacion-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/inflacion-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: inflacion-copilot
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/inflacion-app:${{ github.sha }}
          region: us-central1
